config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  get 'bookings/create'
  get 'theatres/index'
  get 'theatres/show'
  get 'theatres/new'
  get 'theatres/create'
  get 'movies/index'
  get 'movies/show'
  get 'movies/new'
  get 'movies/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :movies, only: [:index, :show, :new, :create]
  resources :theatres, only: [:index, :show, :new, :create]
  resources :bookings, only: [:new, :create]
  root 'movies#index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
# app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :movie
  belongs_to :theatre

  validates :seat_number, presence: true, uniqueness: { scope: :theatre_id, message: "seat already booked in this theatre" }
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookings
    has_many :theatres, through: :bookings
  end

app/models/theatre.rb
class Theatre < ApplicationRecord
    has_many :bookings
    has_many :movies, through: :bookings
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
# app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @movies = Movie.all
    @theatres = Theatre.all
  end

  def create
    movie_id = booking_params[:movie_id]
    theatre_id = booking_params[:theatre_id]
    seat_numbers = booking_params[:seat_numbers].split(',').map(&:strip).map(&:to_i)

    @theatre = Theatre.find(theatre_id)
    existing_seats = Booking.where(theatre: @theatre, seat_number: seat_numbers).pluck(:seat_number)
    available_seats = seat_numbers - existing_seats

    if existing_seats.any?
      redirect_to new_booking_path, alert: "The following seats are already booked: #{existing_seats.join(', ')}"
      return
    end

    if (Booking.where(theatre: @theatre).count + available_seats.size) > @theatre.capacity
      redirect_to new_booking_path, alert: 'Theatre does not have enough capacity for these bookings.'
      return
    end

    Booking.transaction do
      available_seats.each do |seat_number|
        Booking.create!(movie_id: movie_id, theatre_id: theatre_id, seat_number: seat_number)
      end
    end

    redirect_to movie_path(movie_id), notice: 'Bookings were successfully created.'
  end

  private

  def booking_params
    params.require(:booking).permit(:movie_id, :theatre_id, :seat_numbers)
  end
end

app/controllers/movies_controller.rb
# app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :description)
  end
end

app/controllers/theatres_controller.rb
# app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  def index
    @theatres = Theatre.all
  end

  def show
    @theatre = Theatre.find(params[:id])
  end

  def new
    @theatre = Theatre.new
  end

  def create
    @theatre = Theatre.new(theatre_params)
    if @theatre.save
      redirect_to @theatre, notice: 'Theatre was successfully created.'
    else
      render :new
    end
  end

  private

  def theatre_params
    params.require(:theatre).permit(:name, :capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<!-- app/views/bookings/new.html.erb -->
<h1>New Booking</h1>

<% if alert %>
  <p style="color: red;"><%= alert %></p>
<% end %>

<%= form_with url: bookings_path, local: true do |form| %>
  <p>
    <%= form.label :movie_id %><br>
    <%= form.collection_select :movie_id, @movies, :id, :title %>
  </p>
  <p>
    <%= form.label :theatre_id %><br>
    <%= form.collection_select :theatre_id, @theatres, :id, :name %>
  </p>
  <p>
    <%= form.label :seat_numbers, "Seat Numbers (comma-separated)" %><br>
    <%= form.text_field :seat_numbers %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back to Movies', movies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieTicketBooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies</h1>
<%= link_to 'New Movie', new_movie_path %>
<ul>
  <% @movies.each do |movie| %>
    <li><%= link_to movie.title, movie %></li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<h1>New Movie</h1>
<%= form_with model: @movie, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back to Movies', movies_path %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<p><%= @movie.description %></p>
<%= link_to 'Book Ticket', new_booking_path %>
<%= link_to 'Back to Movies', movies_path %>

app/views/theatres/create.html.erb
<h1>Theatres#create</h1>
<p>Find me in app/views/theatres/create.html.erb</p>

app/views/theatres/index.html.erb
<h1>Theatres</h1>
<%= link_to 'New Theatre', new_theatre_path %>
<ul>
  <% @theatres.each do |theatre| %>
    <li><%= link_to theatre.name, theatre %></li>
  <% end %>
</ul>

app/views/theatres/new.html.erb
<h1>New Theatre</h1>
<%= form_with model: @theatre, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :capacity %><br>
    <%= form.number_field :capacity %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back to Theatres', theatres_path %>

app/views/theatres/show.html.erb
<h1><%= @theatre.name %></h1>
<p>Capacity: <%= @theatre.capacity %></p>
<%= link_to 'Back to Theatres', theatres_path %>